apiVersion: v1
kind: Namespace
metadata:
  name: aurora-pipeline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aurora-config
  namespace: aurora-pipeline
data:
  PIPELINE_ENABLED: "true"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  MAX_RETRIES: "3"
  RUN_FREQUENCY: "0 */12 * * *"  # Every 12 hours
---
apiVersion: v1
kind: Secret
metadata:
  name: aurora-secrets
  namespace: aurora-pipeline
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/aurora"
  OPENAI_API_KEY: ""  # Set your keys
  VOICE_API_KEY: ""
  VIDEO_API_KEY: ""
  TWITTER_API_KEY: ""
  YOUTUBE_API_KEY: ""
  LINKEDIN_API_KEY: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-pipeline
  namespace: aurora-pipeline
  labels:
    app: aurora-pipeline
spec:
  replicas: 2  # Use 2 replicas for high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: aurora-pipeline
  template:
    metadata:
      labels:
        app: aurora-pipeline
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: aurora-pipeline
      containers:
      - name: aurora-pipeline
        image: aurora-pipeline:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: aurora-config
        - secretRef:
            name: aurora-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: logs
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - aurora-pipeline
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: aurora-pipeline-service
  namespace: aurora-pipeline
  labels:
    app: aurora-pipeline
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: aurora-pipeline
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aurora-pipeline-hpa
  namespace: aurora-pipeline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aurora-pipeline
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aurora-pipeline-pdb
  namespace: aurora-pipeline
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: aurora-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: aurora-pipeline
  namespace: aurora-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aurora-pipeline
  namespace: aurora-pipeline
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aurora-pipeline
  namespace: aurora-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aurora-pipeline
subjects:
- kind: ServiceAccount
  name: aurora-pipeline
  namespace: aurora-pipeline
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aurora-pipeline
  namespace: aurora-pipeline
spec:
  selector:
    matchLabels:
      app: aurora-pipeline
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aurora-alerts
  namespace: aurora-pipeline
data:
  alerts.yaml: |
    groups:
    - name: aurora-pipeline
      interval: 30s
      rules:
      - alert: AuroraPipelineDown
        expr: up{job="aurora-pipeline"} == 0
        for: 1m
        annotations:
          summary: "Aurora Pipeline is down"
      - alert: AuroraPipelineHighErrorRate
        expr: rate(aurora_pipeline_errors_total[5m]) > 0.05
        for: 5m
        annotations:
          summary: "Aurora Pipeline error rate > 5%"
      - alert: AuroraPipelineHighMemory
        expr: container_memory_usage_bytes{pod=~"aurora-pipeline.*"} / 524288000 > 0.9
        for: 2m
        annotations:
          summary: "Aurora Pipeline memory usage > 90%"
